### ISSUE TITLE
Между линиями получается 2 пикс:(

### ISSUE THREAD

**Issue by denver411** [MiMisar/HomeWork8#1]
https://github.com/MiMisar/HomeWork8/blob/fa5b835bb07f5654c28c3cedced874b8a77c2b7f/style.css#L142

А надо 5:)

**Comment by MiMisar** [comment]
Исправил. Делал изначально -12рх, но что-то подумал, что расстояние больше, чем надо)

**Comment by denver411** [comment]
Теперь хорошо
