### ISSUE TITLE
Попробуй сделать формат, как в предыдущем абзаце

### ISSUE THREAD

**Issue by denver411** [MiMisar/HomeWork8#2]
https://github.com/MiMisar/HomeWork8/blob/fa5b835bb07f5654c28c3cedced874b8a77c2b7f/style.css#L159

Но это придирки, можно и не делать:)

**Comment by MiMisar** [comment]
Имеешь ввиду, чтобы номера были за блоком? Пробовал, не получается =( Попробую еще что-нибудь)

**Comment by denver411** [comment]
position тебе в помощь:)

**Comment by MiMisar** [comment]
Спасибо) Проверяй.

**Comment by denver411** [comment]
Так мне больше нравиться
