### ISSUE TITLE
Вопрос по формату

### ISSUE THREAD

**Issue by denver411** [MiMisar/HomeWork8#3]
https://github.com/MiMisar/HomeWork8/blob/fa5b835bb07f5654c28c3cedced874b8a77c2b7f/style.css#L182

Здесь я бы тоже форматирование поправил

**Comment by MiMisar** [comment]
Попробую =)

**Comment by denver411** [comment]
Круто. Я бы еще звездочки по центру строки разместил (ниже, чем сейчас)

**Comment by MiMisar** [comment]
Добавил "margin-top: 4px;", так верно будет? Проверил, вроде хорошо получилось.

**Comment by denver411** [comment]
Я бы top использовал. Но можно и марджин

С уважением, Денис Жебов

**Comment by MiMisar** [comment]
top в первую очередь попробовал, но * становиться только 1 и надо указывать размер от верха страницы.
